
# The package documentation uses desc::desc_get() to get the description,
# instead of relying on autogenerated description. This is done in order to get
# markdown parsing and facilitate adding extra text to the package doc in
# addition to the text from the DESCRIPTION file.


#' @description
#' `r desc::desc_get("Description")`
#'
#' For more information, see vignette("zmisc").
#'
#' @docType package
#' @name zmisc
#' @md
#' @keywords internal
"_PACKAGE"


# The following block is used by usethis to automatically manage
# roxygen namespace tags. Modify with care!
## usethis namespace: start
## usethis namespace: end
NULL
